# Stage 1: Build the Gradle project
FROM gradle:8-jdk21 AS build
WORKDIR /app

# 1. Copy the top-level Gradle wrapper and configuration files
COPY gradlew build.gradle* settings.gradle* gradle.properties* ./
COPY gradle ./gradle

# 2. Copy the source code for the backend modules
COPY shared ./shared
COPY server ./server

# 3. Use installDist to package the app, dependencies, and startup scripts
RUN ./gradlew :server:installDist -x test --no-daemon

# Stage 2: Create the lightweight runtime container
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

# 4. Copy the fully packaged distribution from the build stage
# installDist puts everything into build/install/<project-name>
COPY --from=build /app/server/build/install/server /app/

# Expose the port your custom server listens on
EXPOSE 8080

# 5. Run the startup script generated by Gradle
# Note: The script name usually matches the module name ('server')
CMD ["./bin/server"]