org.gradle.configuration-cache=true

# Build configuration for the client
# Whether to trust all certificates. If you create your own keystore for local development, you should set this to true or the client won't allow you to connect to the server.
trustAllCertificates=true
# The base URL of the api on the server
baseUrl=https://localhost:6767/api
